# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e0dd20f37dd700aea4ca2c257bf97d33f47c2bff3485c4104f47be0460437c68983b5b063356dabf85554bcd7ed61341e976d63f8c9c7a5d6327dc3e7fb709d3

test:
  secret_key_base: de218345bb134e2d1ca209f8275241d5d36492de3773f7baa53b48eb2e44fe1a1af48a1c16f11e8468bd38e4a494fb951a36ea28241e1fee484b45114d132133

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
